// 10-Step Guided Story Sequence for SIEGER OHC Material-Handling Simulation

export const STORY_STEPS = [
  {
    step: 1,
    title: 'Doff Cycle Completion',
    description: 'Production Machine M05 completes its yarn spinning cycle and reaches 100/100 doff count.',
    targetId: 'M05',
    targetType: 'machine',
    badge: 'DOFF TRIGGER',
    details: 'Machine M05 signals high-priority material unload request for 34s SCHY yarn cones.',
  },
  {
    step: 2,
    title: 'FIFO Queue Insertion',
    description: 'Loading request is registered into position 1 of the 4-slot FIFO Queue.',
    targetId: 'fifo-queue',
    targetType: 'queue',
    badge: 'FIFO QUEUE',
    details: 'System enforces strict First-In First-Out order. Max active queue limit is 4.',
  },
  {
    step: 3,
    title: 'Empty Basket Identification',
    description: 'Conveyor PLC scans the 280-basket fleet and allocates available Empty Basket B152.',
    targetId: 'B152',
    targetType: 'basket',
    badge: 'EMPTY BASKET FOUND',
    details: 'Empty baskets are mandatory before loading can initiate. B152 enters loader bay.',
  },
  {
    step: 4,
    title: 'Loader Assignment',
    description: 'Loader L05 is assigned to Machine M05 and docks Empty Basket B152.',
    targetId: 'L05',
    targetType: 'loader',
    badge: 'LOADER ASSIGNED',
    details: 'Loading arms engage with the ring-frame spindle discharge mechanism.',
  },
  {
    step: 5,
    title: 'Cone Transfer & Basket Loading',
    description: 'B152 is loaded with 32 cones of Variant B (34s SCHY). Machine M05 resets.',
    targetId: 'L05',
    targetType: 'loader',
    badge: 'LOADING COMPLETE',
    details: 'All 32 cones securely positioned in conical retaining pegs. M05 resumes new doff.',
  },
  {
    step: 6,
    title: 'Conveyor Rail Dispatch',
    description: 'Loaded Basket B152 transitions onto the main OHC overhead conveyor rail.',
    targetId: 'B152',
    targetType: 'conveyor',
    badge: 'OHC IN TRANSIT',
    details: 'Motorized trolley drives basket at 45 m/min along the ceiling-mounted steel track.',
  },
  {
    step: 7,
    title: 'Arrival at Unloading Approach Zone',
    description: 'B152 traverses the factory hall and approaches the 4 Dynamic Unloaders.',
    targetId: 'B152',
    targetType: 'conveyor',
    badge: 'APPROACH ZONE',
    details: 'Optical sensors detect B152 and request dynamic unloader allocation.',
  },
  {
    step: 8,
    title: 'Dynamic Unloader U03 Allocation',
    description: 'Dynamic Unloader U03 is dynamically assigned to receive Basket B152.',
    targetId: 'U03',
    targetType: 'unloader',
    badge: 'DYNAMIC ASSIGNMENT',
    details: 'Unloaders are dynamic (not hardcoded to variants), maximizing station utilization.',
  },
  {
    step: 9,
    title: 'Full Unloading & Pallet Stacking',
    description: 'U03 unloads all 32 cones into Pallet Station P03. Cone count in B152 drops to 0.',
    targetId: 'U03',
    targetType: 'unloader',
    badge: 'CONES UNLOADED',
    details: 'Cones are transferred to high-density shipping pallets. No cone returns back.',
  },
  {
    step: 10,
    title: 'Basket Marked EMPTY & Cycle Closes',
    description: 'B152 is marked EMPTY and routed to the empty basket return buffer for immediate reuse.',
    targetId: 'B152',
    targetType: 'basket',
    badge: 'BASKET REUSED',
    details: 'Closed-loop economy: B152 is instantly ready for the next machine doff request!',
  },
];
